#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Spec: 003 - Repository Pulse Dashboard Phase 2

set -e

echo "========================================"
echo "Repository Pulse Dashboard - Phase 2"
echo "Metrics Calculation Engine Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Navigate to project root
cd /Users/ambrealismwork/Desktop/Coding-Projects/github-repo-explorer

echo ""
echo "Step 1: Verify Dependencies"
echo "----------------------------------------"

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js not found. Please install Node.js 18+${NC}"
    exit 1
fi

NODE_VERSION=$(node -v)
echo -e "${GREEN}Node.js: ${NODE_VERSION}${NC}"

# Check npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}npm not found.${NC}"
    exit 1
fi

NPM_VERSION=$(npm -v)
echo -e "${GREEN}npm: ${NPM_VERSION}${NC}"

echo ""
echo "Step 2: Install Dependencies"
echo "----------------------------------------"

npm install

echo ""
echo "Step 3: Verify Existing Tests Pass"
echo "----------------------------------------"

npm test 2>&1 | tail -10

echo ""
echo "Step 4: Create PulseDashboard Directory (if needed)"
echo "----------------------------------------"

if [ ! -d "src/js/components/PulseDashboard" ]; then
    mkdir -p src/js/components/PulseDashboard
    echo -e "${GREEN}Created: src/js/components/PulseDashboard/${NC}"
else
    echo -e "${YELLOW}Directory already exists: src/js/components/PulseDashboard/${NC}"
fi

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Project Structure:"
echo "  src/js/components/PulseDashboard/"
echo "    - constants.js (to create)"
echo "    - PulseCalculator.js (to create)"
echo "    - index.js (to create)"
echo ""
echo "  src/js/__tests__/"
echo "    - PulseDashboard.test.js (to create)"
echo ""
echo "Commands:"
echo "  npm run dev        # Start dev server"
echo "  npm test           # Run tests once"
echo "  npm run test:watch # Run tests in watch mode"
echo ""
echo "Reference Files:"
echo "  src/js/components/HealthScore.js    # Calculation pattern"
echo "  src/js/__tests__/HealthScore.test.js # Test pattern"
echo "  docs/repository-pulse-dashboard-implementation-plan.md"
echo ""
