#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Feature: Repository Pulse Dashboard - Phase 1: Data Collection & API Layer

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Project root
PROJECT_ROOT="/Users/ambrealismwork/Desktop/Coding-Projects/github-repo-explorer"

# Change to project root
cd "$PROJECT_ROOT"

# Check Node.js is available
if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js is not installed${NC}"
    exit 1
fi

# Check npm is available
if ! command -v npm &> /dev/null; then
    echo -e "${RED}npm is not installed${NC}"
    exit 1
fi

# Check if node_modules exists
if [ ! -d "node_modules" ]; then
    echo "Installing dependencies..."
    npm install
fi

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting Vite dev server..."

# Start Vite dev server in background
npm run dev &
VITE_PID=$!

# Wait for Vite to be ready
wait_for_service 5173 "Vite Dev Server"

# ============================================
# VERIFY TEST ENVIRONMENT
# ============================================

echo ""
echo "Verifying test environment..."

# Run tests to verify setup
npm test -- --run 2>&1 | tail -5

if [ $? -eq 0 ]; then
    echo -e "${GREEN}Test suite passed${NC}"
else
    echo -e "${YELLOW}Warning: Some tests may have failed${NC}"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:5173"
echo ""
echo "Commands:"
echo "  npm run dev      - Start dev server"
echo "  npm test         - Run tests"
echo "  npm run build    - Production build"
echo ""
echo "Vite PID: $VITE_PID"
echo "To stop: kill $VITE_PID"
echo ""
